before_script:
    - docker-compose build
    - docker-compose start

after_script:
    - docker-compose down

stages:
    - quality

quality:
    stage: quality
    script:
        - php bin/phpunit -c xvolutionscms/