version: '3'
services:
  db:
    image: mysql/mysql-server:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    build: .
    command: bash -c "cp xvolutions/config/parameters.yml.dist xvolutions/config/parameters.yml && composer update && php xvolutions/console doctrine:schema:create && php xvolutions/console xvolutions:admin:initiate admin Administrator oko admin && php xvolutionscms/console server:run 0.0.0.0:8000 --docroot=public_html"
    ports:
      - "${WEB_PORT}:8000"
    links:
      - db
    volumes:
      - .:/host
